source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import SignUp, UserDetailView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', SignUp.as_view(), name='create'),
    path('profile/<pk>/', UserDetailView.as_view(), name='user_detail'),

]

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import SignUp, UserDetailView
# from webapp.views import IndexView\
    # , AnnounceCreateView, AnnounceDetailView, AnnounceUpdateView, AnnounceDeleteView

app_name = 'webapp'

urlpatterns = [
    # path('', IndexView.as_view(), name='index'),
    # path('announce/create/', AnnounceCreateView.as_view(), name='announce_create'),
    # path('announce/detail/<int:pk>/', AnnounceDetailView.as_view(), name='announce_detail'),
    # path('announce/update/<int:pk>/', AnnounceUpdateView.as_view(), name='announce_update'),
    # path('announcements/delete/<int:pk>/', AnnounceDeleteView.as_view(), name='announce_delete'),
]

source/webapp/models.py
from django.db import models

ANNOUNCEMENT_STATUS_CHOICES = (
    ('active', 'Активный'),
    ('completed', 'Завершенный'),
)

ANNOUNEMENT_TYPE_CHOICES = (
    ('client', 'Клиент'),
    ('driver', 'Водитель'),
)
OBLASTI_CHOICES = (
    ('Bishkek', 'Бишкек'),
    ('Chui', 'Чуй'),
    ('Talas', 'Талас'),
    ('Naryn', 'Нарын'),
    ('Issykkul', 'Иссыкуль'),
    ('Osh', 'Ош'),
    ('Jalal-Abad', 'Жалал-Абад'),
    ('Batken', 'Баткен')
)


class Announcements(models.Model):
    author = models.ForeignKey('auth.User', related_name='announcement', on_delete=models.CASCADE, verbose_name='Автор')
    type = models.CharField(max_length=50, choices=ANNOUNEMENT_TYPE_CHOICES, verbose_name='Тип')
    description = models.CharField(max_length=50, null=True, blank=True, verbose_name='Описание')
    place_from = models.CharField(max_length=100, choices=OBLASTI_CHOICES, verbose_name='Откуда')
    place_to = models.CharField(max_length=100, choices=OBLASTI_CHOICES,  verbose_name='Куда')
    departure_time = models.DateTimeField(verbose_name='Когда')
    seats = models.IntegerField(verbose_name='Количество мест')
    luggage = models.CharField(null=True, blank=True, max_length=100, verbose_name='Багаж')
    car_model = models.CharField(max_length=50, null=True, blank=True, verbose_name='Модель авто')
    car_number = models.CharField(max_length=50, null=True, blank=True, verbose_name='Номер авто')
    price = models.IntegerField(null=True, blank=True, verbose_name='Цена')
    photo = models.ImageField(upload_to='ads_photo', null=True, blank=True, verbose_name='Фото')
    clients = models.ManyToManyField('auth.User', null=True, blank=True, related_name='experts',
                                     verbose_name='Область аккредитации')
    status = models.CharField(max_length=50, choices=ANNOUNCEMENT_STATUS_CHOICES, verbose_name='Статус')

    def __str__(self):
        return self.description

source/webapp/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse

from webapp.models import Announcements


# class IndexView(ListView):
#     model = Announcements
#     template_name = 'index.html'
#     context_object_name = 'announcements'

    # def get_queryset(self, *args, **kwargs):
    #         return Announcements.objects.filter(user__profile__driver__status='free')


# class AnnounceCreateView(CreateView):
#     model = Ad
#     template_name = 'announce_create.html'
#     # form_class = AnnounceCreationForm
#     fields = ['direction', 'time', 'seats', 'luggage', 'place_from', 'place_to', 'car_number', 'car', 'price']

    # def get_form_kwargs(self):
    #     print(self.request.user)
    #     kwargs = super().get_form_kwargs()
    #     kwargs['author'] = self.request.user
    #     return kwargs

    # def form_valid(self, form):
    #     self.object = form.save(commit=False)
    #     user = self.request.user
    #     # mobile_phone = form.cleaned_data['mobile_phone']
    #     self.object.direction = form.cleaned_data['direction']
    #     self.object.time = form.cleaned_data['time']
    #     self.object.seats = form.cleaned_data['seats']
    #     self.object.luggage = form.cleaned_data['luggage']
    #     self.object.place_from = form.cleaned_data['place_from']
    #     self.object.place_to = form.cleaned_data['place_to']
    #     self.object.car_number = form.cleaned_data['car_number']
    #     self.object.car = form.cleaned_data['car']
    #     self.object.price = form.cleaned_data['price']
    #     # if mobile_phone:
    #     #     self.object.mobile_phone = mobile_phone
    #     # else:
    #     #     self.object.phone = self.request.user.profile.phone_number
    #     self.object.user_id = user.pk
    #     self.object.save()
    #     return HttpResponseRedirect(self.get_success_url())
    #
    # def get_success_url(self):
    #     return reverse('webapp:index')


# class AnnounceDetailView(DeleteView):
#     model = Ad
#     template_name = 'announce_detail.html'
#     context_object_name = 'announce'
#
#
# class AnnounceUpdateView(UpdateView):
#     model = Ad
#     template_name = 'change.html'
#     fields = ['direction', 'time', 'seats', 'luggage', 'place_from', 'place_to', 'car_number', 'car', 'price']
#     context_object_name = 'announce'
#
#     def get_success_url(self):
#         return reverse('webapp:index')
#
#
# class AnnounceDeleteView(DeleteView):
#     model = Ad
#     template_name = 'delete.html'
#
#     def get_success_url(self):
#         return reverse('webapp:index')

source/webapp/templates/announce_create.html
{#{% extends 'base.html' %}#}
{#{% block content %}#}
{#        <h1 class="text-center">Подать объявление</h1>#}
{#        <form action="{% url 'webapp:announce_create' %}" method="post" enctype="multipart/form-data">#}
{#            {% include "partial/form.html" %}#}
{#            <p class="text-center"><input type="submit" value="Создать" class="btn btn-success"></p>#}
{#        </form>#}
{#{% endblock %}#}

source/webapp/templates/announce_detail.html
{#{% extends 'base.html' %}#}
{#{% load staticfiles %}#}
{#{%  block content %}#}
{#    <div class="card" style="width: 18rem;">#}
{#    {% if  ad.image.all.first.photos.url %}#}
{#        <img src="{{ ad.image.all.first.photos.url }}" class="card-img-top" alt="...">#}
{#        {% else %}#}
{#        <img src="/uploads/no_photo.jpg" class="card-img-top" alt="...">#}
{#        {% endif %}#}
{#  <div class="card-body">#}
{#    <h5 class="card-title">Направление: {{ announce.direction }}</h5>#}
{#    <p class="card-text">Время: {{ announce.time }}</p>#}
{#      <p class="card-text">Места: {{ announce.seats }}</p>#}
{#      <p class="card-text">Багаж: {{ announce.luggage }}</p>#}
{#      <p class="card-text">Автор:  <a href="{% url 'accounts:user_detail' ad.author.pk %}">{{ ad.author}}</a></p>#}
{#      <tr data-href="{% url 'accounts:user_detail' use.pk %}">#}
{#    <a href="#" class="btn btn-primary">Go somewhere</a>#}
{#      <a href="{% url 'webapp:image_add' ann.pk %}" class="btn btn-primary">Добавить фото</a>#}
{#      <a href="{% url 'webapp:announce_detail' ad.pk%}" class="btn btn-success">Посмотреть</a>#}
{#      <a href="{% url 'webapp:announce_update' announce.pk%}" class="btn btn-warning">Редактировать</a>#}
{#      <a href="{% url 'webapp:announce_delete' announce.pk %}" class="btn btn-danger">Удалить</a>#}
{#      {% if request.user.is_authenticated %}#}
{#            {% include 'partial/favorites_buttons.html' %}#}
{#        {% endif %}#}
{#  </div>#}
{#</div>#}
{#    <script src="{% static 'js/main.js' %}"></script>#}
{#{% endblock %}#}

source/webapp/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "/css/style.css" %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    {% block style_links %}{% endblock %}
</head>
<body>
<div class="container mt-3">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item active">
{#                <a class="nav-link" href="{% url 'webapp:index' %}">Home <span class="sr-only">(current)</span></a>#}
              </li>
                {% block menu %}{% endblock %}
                <li class="nav-item menu-right">
                        {% if request.user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:user_detail' request.user.pk %}">Привет, {{ request.user }}!</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout'  %}">Выйти</a></li>
{#                            <li class="nav-item"><a class="nav-link" href="{% url 'webapp:announce_create'  %}">Подать объявление</a></li>#}
                        {% else %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login'  %}">Войти</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:create' %}">Регистрация</a></li>
                        {% endif %}
                </li>
            </ul>
          </div>
        </nav>
    {% block content %}

    {% endblock %}
</div>

<script src={% static "/js/jquery-3.4.1.min.js"%}></script>
<script src="{% static '/js/main.js' %}"></script>
<script src={% static "/js/popper.min.js"%}></script>
<script src={% static "/js/bootstrap.min.js"%}></script>
{% block script %}{% endblock %}
</body>
</html>

source/webapp/templates/change.html
{#{% extends 'base.html' %}#}
{#{% block title %}Обновить{% endblock %}#}
{#{% block content %}#}
{#    <h1>Обновление {{ title }}</h1>#}
{#    <form method="POST">#}
{#        {% include 'partial/form.html' %}#}
{#        <p class="text-center"><input type="submit" value="Обновить" class="btn btn-primary"></p>#}
{#    </form>#}
{#    {% for message in messages %}#}
{#        <h3 class="text-center" style="color: red">#}
{#            {{ message }}#}
{#        </h3>#}
{#    {% endfor %}#}
{#{% endblock %}#}

source/webapp/templates/delete.html
{#{% extends "base.html" %}#}
{#{% block title %}Удалить {{ title }}{% endblock %}#}
{#{% block content %}#}
{#    <h3>Вы уверены что хотите удалить {{ title }} :<br>"{{ object.direction }}"?</h3>#}
{#    <form method="POST"  class="text-center">#}
{#        {% csrf_token %}#}
{#        <div class="confirm d-flex justify-content-center">#}
{#            <p><input type="submit" value="Да" class="btn btn-danger mt-5"></p>#}
{#        </div>#}
{#    </form>#}
{#{% endblock %}#}

source/webapp/templates/index.html
{#{% extends 'base.html' %}#}
{##}
{#{% block content %}#}
{#    <section>#}
{#        <h1>Объявления:</h1>#}
{#        {% for announcement in announcements %}#}
{#            <div class="card" style="width: 18rem;">#}
{#            {% if  announcement.image.all.first.photos.url %}#}
{#                <img src="{{ ad.image.all.first.photos.url }}" class="card-img-top" alt="...">#}
{#            {% else %}#}
{#                <img src="/uploads/no_photo.jpg" class="card-img-top" alt="...">#}
{#            {% endif %}#}
{#          <div class="card-body">#}
{#            <h5 class="card-title">Направление: {{ announcement.description }}</h5>#}
{#            <p class="card-text">Время: {{ announcement.departure_time }}</p>#}
{#              <p class="card-text">Места: {{ announcement.seats }}</p>#}
{#              <p class="card-text">Багаж: {{ announcement.luggage }}</p>#}
        {#      <p class="card-text">Автор:  <a href="{% url 'accounts:user_detail' ad.author.pk %}">{{ ad.author}}</a></p>#}
        {#      <tr data-href="{% url 'accounts:user_detail' use.pk %}">#}
        {#    <a href="#" class="btn btn-primary">Go somewhere</a>#}
        {#      <a href="{% url 'webapp:image_add' ann.pk %}" class="btn btn-primary">Добавить фото</a>#}
{#              <a href="{% url 'webapp:announce_detail' ad.pk%}" class="btn btn-success">Посмотреть</a>#}
{#              <a href="{% url 'webapp:announce_update' ad.pk%}" class="btn btn-warning">Редактировать</a>#}
        {#      {% if request.user.is_authenticated %}#}
        {#            {% include 'partial/favorites_buttons.html' %}#}
        {#        {% endif %}#}
{#          </div>#}
{#</div>#}
{#    {% endfor %}#}
{#    </section>#}
{#    <section>#}
{#            </p>#}
{#            <hr/>#}
{#    </section>#}
{#{% endblock %}#}